- name: Install Google Linux signing key.
  tags: chrome, ubuntu
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Install Google Chrome source list.
  tags: chrome, ubuntu
  apt_repository:
      repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      filename: "google-chrome"
      state: present
      update_cache: yes

- name: Install Google Chrome.
  apt:
    name: "google-chrome-stable"
    state: present
    update_cache: yes
    force_apt_get: yes
