- name: Install the slack package
  tags: vscode, ubuntu, debian
  vars:
    slack_version: "4.39.95"
  apt:
    deb: https://downloads.slack-edge.com/desktop-releases/linux/x64/{{slack_version}}/slack-desktop-{{slack_version}}-amd64.deb
    state: present
    update_cache: yes
    force_apt_get: yes
